language: r
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
r_binary_packages:
- rgl
os:
- linux
- osx
osx_image: xcode9
services:
- xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
- jags_install || true;
- v8_install || true;
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- export cmake_version="3.11"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" || "${PACKAGE_NAME}" == "qMRI" ]]; then gsl_install
  ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: ocJC2JJTTumaH9oMaXKYCIxLMN4T6hDIQfTq2Q+cnnH0FVUJhdiAFwyOkwFcUc31Y9WaHpvp6KqiKK/AaiQ/e7FiF6BYyEwq38+uZ34pSoYUM8XGC63LIPPDtyIcRGEfUZLZ9hdFpfx3qOuNUtn0Kxj44vNBVfsD/L1Af1N2CpjbZapEFo2A1SCOstveYh5fdwDprlOcjWkhO9MZjp0AX8K31rRFAySVIJCcmUMWupa1KJFBza1jey7EsTw8sJWpX1W7lX2ggwNgfVES3r95nBlg1XgUGqJ50RB0LrMfmvSGyJrME5vhsR/9+HhN5vMTx98RX7EiUU0eJ6bY3w/ok+CtL9RfWLxOfghD/kEZWpmyxDOMZoQMNyXPXrYAheBSFrKMsTKIs3LvW8+kxwq4q3WusuXQ9J2ncdaiMilFwOaNlUl8N9T8OYENuymQdi/sJgKMAVmhNn9LYrItppMd3MsYCvbMUUbUT/tGs+Xlw2SewOTOris6nXXuseXxCxc2A8gP6uOP9yhOlbX2olcjwBFAEwFH3zU2iNy1NxYFKsUSxUJJOyE8hkK7gYF1Er9ky1KfBjIN4qlVooTYwzqBhWhx4hPY7iPAixCw11Q8vEro5ChGcgZfdq6o7Bk6EHz0eIawG1pLq7AqKfWvc+ofLmp/TfBTTqlQq16WhzIeYsU=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi

#neuroc.deps version (SHA): 6302102